Repository puppetlabs/puppetlabs-ibm_installation_manager, pull requests merged in 2018-08, with the labels that each got.

#85 (FM-7260) - Addition of support for ubuntu 18.04
  metadata.json
Labels: feature

#86 (maint) - Removal of support for deprecated OS debian 6 and 7
  metadata.json
Labels: backwards-incompatible

#88 (maint) Update README to include REFERENCE.md url
  README.md
Labels: maintenance
